import type { Metadata } from 'next'
import './globals.css'
import Content from './layouts/Content'
import Backdrop from './components/common/Backdrop'
import { Tooltip } from './components/tooltip/Tooltips'
import Providers from './contexts/provider/provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={'font-roboto'}>
          <Content>
            { children }  
          </Content>
          <Backdrop />
          <Tooltip />
        </body>
      </Providers>
    </html>
  )
}
