import type { Metadata } from "next";
import Providers from "./_contexts";
import Content from "./_layouts/Content";
import "./globals.css";
import { Data } from "./_server/data";
import SiteEntry from "./_components/siteEntry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-roboto overflow-y-scroll h-full">
      <body className="overflow-y-visible h-full">
        <Data />
        <SiteEntry>{children}</SiteEntry>
      </body>
    </html>
  );
}
