import type { Metadata } from "next";
import Providers from "./_contexts";
import Content from "./_layouts/Content";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <Content>{children}</Content>
    </Providers>
  );
}
