export enum Pagination {
  LIMIT_FOLLOWERS = 10,
  LIMIT_FOLLOWING = 10,
  LIMIT_COMMENTS = 10,
  LIMIT_POSTS = 9,
}

export enum STATUS_CODES {
  OK = 200,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  NOT_FOUND = 404,
  SERVER_ERROR = 500,
}